# Generated by Django 3.2.5 on 2021-11-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_url',
            field=models.TextField(default='https://loisirs.saint-georges.ca/wp-content/uploads/2021/03/Titre-Activites-CSLD.png'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='photo_url',
            field=models.TextField(default='https://loisirs.saint-georges.ca/wp-content/uploads/2021/03/Titre-Activites-CSLD.png'),
        ),
    ]
