# Generated by Django 3.2.5 on 2021-09-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
